version: "3.8"
services:
  harbor-mongo-keys:
    image: depop/openssl-bats
    volumes:
      - harbor-mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  harbor1:
    image: percona/percona-server-mongodb:7.0
    container_name: harbor1
    hostname: harbor1
    ports:
      - "27017:27017"
    volumes:
      - harbor-mongo-keys:/opt/keyfile
      - harbor-mongo-data-0:/data/db
    env_file:
      ./mongod.env
    networks:
      - harbor-network
    command: "mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet hrs"
    depends_on:
        - harbor-mongo-keys
  harbor2:
    image: percona/percona-server-mongodb:7.0
    container_name: harbor2
    hostname: harbor2
    ports:
      - "27018:27017"
    volumes:
      - harbor-mongo-keys:/opt/keyfile
      - harbor-mongo-data-1:/data/db
    env_file:
      ./mongod.env
    networks:
      - harbor-network
    command: "mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet hrs"
    depends_on:
        - harbor-mongo-keys
  harbor3:
    image: percona/percona-server-mongodb:7.0
    container_name: harbor3
    hostname: harbor3
    ports:
      - "27019:27017"
    volumes:
      - harbor-mongo-keys:/opt/keyfile
      - harbor-mongo-data-2:/data/db
    env_file:
      ./mongod.env
    networks:
      - harbor-network
    command: "mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet hrs"
    depends_on:
        - harbor-mongo-keys
  harbor4:
    image: percona/percona-server-mongodb:7.0
    container_name: harbor4
    hostname: harbor4
    ports:
      - "27020:27017"
    volumes:
      - harbor-mongo-keys:/opt/keyfile
      - harbor-mongo-data-3:/data/db
    env_file:
      ./mongod.env
    networks:
      - harbor-network
    command: "mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet hrs"
    depends_on:
        - harbor-mongo-keys
  

volumes:
  harbor-mongo-keys:
  harbor-mongo-data-0:
  harbor-mongo-data-1:
  harbor-mongo-data-2:
  harbor-mongo-data-3:

networks:
  harbor-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24