version: '3.4'

services:
  harbordb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harbordb
    hostname: harbordb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - harbordb_data:/data/db
    command: ["--auth", "--bind_ip_all","--keyFile", "/opt/keyfile/mongo-keyfile", "--rplSet", "rs0" ]

volumes:
  harbordb_data: