version: "3"

services:
  mongodb:
    image: percona/percona-server-mongodb:6.0
    container_name: harbordb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./config/mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod", "--auth", "--config", "/etc/mongod.conf"]