version: "3"
services:
  rs101:
    image: percona/percona-server-mongodb:7.0
    container_name: rs101
    hostname: rs101
    ports:
      - "27017:27017"
    networks:
      - my-network
    command: "--port=27017 --replSet rs"

  rs102:
    image: percona/percona-server-mongodb:7.0
    container_name: rs102
    hostname: rs102
    ports:
      - "28017:28017"    
    networks:
      - my-network
    command: "--port=28017 --replSet rs"

  rs103:
    image: percona/percona-server-mongodb:7.0
    container_name: rs103
    hostname: rs103
    ports:
      - "29017:29017"    
    networks:
      - my-network
    command: "--port=29017 --replSet rs"

networks:
  my-network:
    driver: bridge