version: "3"

services:
  mongodb:
    image: percona/percona-server-mongodb:6.0
    container_name: harbordb
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./clusters/db1:/data/db
    entrypoint: ["mongod", "--auth", "--bind_ip_all" ]